apiVersion: v1
kind: Pod
metadata:
  name: uno
spec:
  containers:
    - name: appserver
      image: regwalli001-on.azurecr.io/sqlcmd4centos
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c"]
      args: ["while [ true ]; do sqlcmd -S 10.244.0.2 -U SA -P ABpKJ.mjm1968pups -Q \"select getDate()\"; sleep 1; done"]
  imagePullSecrets:
    - name: myregistrykey
